site_name: Azur3lily's record
docs_dir: docs/青志
nav:
  - 摄影内训: docs.md

theme:
  name: material
  language: zh

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      site_name: Azur3lily's record
      docs_dir: docs/青志

      theme:
        name: material
        language: zh

      markdown_extensions:
        - toc:
            permalink: true
            toc_depth: 4
        - admonition
        - pymdownx.superfences
        - pymdownx.arithmatex:
            generic: true

      plugins:
        - search